[project]
site_name = "FF4j Documentation"
site_description = "Documentation for Feature Flipping for Java (ff4j)"
site_author = "Paul WILLIAMS"
site_url = "https://ff4j.github.io/docs/"
copyright = """
Copyright &copy; 2026 ff4j. All rights reserved.
"""

nav = [
   { "Home" = "index.md" }
 ]

extra_css = ["stylesheets/bootstrap-grid.min.css", "stylesheets/theme.css"]

[project.theme]
logo = "img/ff4j-logo.svg"
favicon = "img/ff4j-logo.svg"
custom_dir = "docs/overrides"
language = "en"
features = [
    "announce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "navigation.footer",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.prune",
    "navigation.sections",
    "navigation.tabs",
    "navigation.tabs.sticky",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
    "toc.follow"
]

[[project.theme.palette]]
scheme = "slate"
primary = "custom"
accent = "custom"
