[project]
site_name = "FF4j Documentation"
site_description = "Documentation for Feature Flipping for Java (ff4j)"
site_author = "Paul WILLIAMS"
site_url = "https://ff4j.github.io/docs/"
copyright = """
Copyright &copy; 2026 ff4j. All rights reserved.
"""

nav = [
  { "Home" = "index.md" },
  { "About" = [
    { "Quick Start" = "pages/about/quickstart/index.md" },
    { "Core Concepts" = [
      { "Architecture" = "pages/about/core-concepts/architecture/index.md" },
      { "Feature" = "pages/about/core-concepts/feature/index.md" },
      { "Feature Store" = "pages/about/core-concepts/feature-store/index.md" },
      { "Property" = "pages/about/core-concepts/property/index.md" },
      { "Property Store" = "pages/about/core-concepts/property-store/index.md" },
      { "Feature Groups" = "pages/about/core-concepts/feature-groups/index.md" },
    ] },
    { "Advanced Concepts" = [
      { "AOP" = "pages/about/advanced-concepts/aop/index.md" },
      { "Audit" = "pages/about/advanced-concepts/audit/index.md" },
      { "Caching" = "pages/about/advanced-concepts/caching/index.md" },
      { "CLI" = "pages/about/advanced-concepts/cli/index.md" },
      { "JMX" = "pages/about/advanced-concepts/jmx/index.md" },
      { "Spring Boot" = "pages/about/advanced-concepts/spring-boot/index.md" }
    ] }
  ] },
  { "Flipping Strategies" = [
    { "Overview" = "pages/flipping-strategies/overview/index.md" },
    { "Blacklist" = "pages/flipping-strategies/blacklist/index.md" },
    { "Client Filter" = "pages/flipping-strategies/client-filter/index.md" },
    { "Dark Launch" = "pages/flipping-strategies/dark-launch/index.md" },
    { "Drools" = "pages/flipping-strategies/drools/index.md" },
    { "Expression" = "pages/flipping-strategies/expression/index.md" },
    { "Office Hour" = "pages/flipping-strategies/office-hour/index.md" },
    { "Ponderation" = "pages/flipping-strategies/ponderation/index.md" },
    { "Release Date" = "pages/flipping-strategies/release-date/index.md" },
    { "Server Filter" = "pages/flipping-strategies/server-filter/index.md" },
    { "Whitelist" = "pages/flipping-strategies/whitelist/index.md" }
  ] },
  { "Security" = [
    { "Apache Shiro" = "pages/security/apache-shiro/index.md" },
    { "Spring" = "pages/security/spring/index.md" }
  ] },
  { "Stores" = [
    { "Overview" = "pages/stores/overview/index.md" },
    { "Archaius" = "pages/stores/archaius/index.md" },
    { "AWS DynamoDB" = "pages/stores/aws-dynamo-db/index.md" },
    { "AWS SSM Parameter Store" = "pages/stores/aws-ssm-parameter-store/index.md" },
    { "Cassandra" = "pages/stores/cassandra/index.md" },
    { "Consul" = "pages/stores/consul/index.md" },
    { "Default" = "pages/stores/default/index.md" },
    { "Ehcache" = "pages/stores/eh-cache/index.md" },
    { "Elasticsearch" = "pages/stores/elastic/index.md" },
    { "JDBC" = "pages/stores/jdbc/index.md" },
    { "MongoDB" = "pages/stores/mongodb/index.md" },
    { "Neo4j" = "pages/stores/neo4j/index.md" },
    { "Redis" = "pages/stores/redis/index.md" },
    { "Spring JDBC" = "pages/stores/spring-jdbc/index.md" }
  ] },
  { "Web" = [
    { "RESTful API" = "pages/web/restful-api/index.md" },
    { "Web Console" = "pages/web/web-console/index.md" }
  ] }
]

extra_css = ["stylesheets/bootstrap-grid.min.css", "stylesheets/theme.css"]

[project.theme]
logo = "img/ff4j-logo.svg"
favicon = "img/ff4j-logo.svg"
custom_dir = "docs/overrides"
language = "en"
features = [
    "announce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "navigation.footer",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.prune",
    "navigation.sections",
    "navigation.tabs",
    "navigation.tabs.sticky",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
    "toc.follow"
]

[[project.theme.palette]]
scheme = "slate"
primary = "custom"
accent = "custom"
